CREATE TABLE `askmilazim`.`members` (
  `id` INT NOT NULL,
  `name` VARCHAR(190) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `remember_token` VARCHAR(100) NULL,
  `activation_token` VARCHAR(100) NULL,
  `forgot_token` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `activated` INT NULL,
  `gender` INT NULL,
  `birth_date` DATE NULL,
  `city_id` INT NULL,
  PRIMARY KEY (`id`));
